### ISSUE TITLE
\csq@mainlang

### ISSUE THREAD

**Issue by svenper** [josephwright/csquotes#35] opened 2019-11-21 07:55 UTC
I need to add `\def\csq@mainlang{german}` to the preamble, or I get errors about it being undefined.

**Comment by josephwright** [comment] 2019-11-21 07:56
Could you add an example? The latest release seems to be working fine for most people.

**Comment by moewew** [comment] 2019-11-21 08:03
Ugh, not again! I thought I had fixed all errors with #28.

Can you please post a full example document that reproduces the issue.
```latex
\documentclass[dutch,ngerman]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}


\begin{document}
Lorem \enquote{ipsum} dolor

\foreignquote{dutch}{Lorem \enquote{dutch} dolor}
\end{document}
```
seems to work just fine. The related issues #30 and #33 should be fixed in the newest version of `csquotes` that is in MikTeX and TeX live.

**Comment by svenper** [comment] 2019-11-21 08:20
The MWEs from those #30 and #33 have no problems. I will try to produce a MWE, so far I have only encountered the issue in a complex document.

Note also that \csq@mainlang corrupts biblatex labels like Ibid.

**Comment by moewew** [comment] 2019-11-21 08:51
I introduced one functional change with `\csq@mainlang` in https://github.com/josephwright/csquotes/commit/de8f6ce7ed964dc2d26de48a4b3b5ee495b60fa8: It now issues an error/warning (depending on the settings) if it can not detect a main document language at all (at the time I thought a user would likely never reach that warning/error since I believed that the relevant macro would only be executed if the multilingual feature is active and that can only be active if `babel` or `polyglossia` is loaded - and then we should be able to detect the main language). Maybe you ran into that? If you don't define `\csq@mainlang` what warnings or errors do you get? Do you load `babel`, `polyglossia` or no language package at all? What language settings do you have active? In what context does `csquotes` throw the error? (Of course I still want to see an MWE, the question is just to get a broad feeling what could be wrong.)

----

> Note also that \csq@mainlang corrupts biblatex labels like Ibid.

That doesn't sound too good either. Can you describe in more detail what you mean by corrupt? Can you reproduce that issue in a short example document?



----


**edit** What strikes me as extremely odd is that `\csq@mainlang` is always guarded with `\ifdef` in https://github.com/josephwright/csquotes/blob/master/csquotes.sty so it can't be called when it is undefined. Furthermore, the `\ifdef`s in `\csq@savelang` should ensure that we don't try to assign an undefined control sequence to `\csq@mainlang`. So I'm wondering if it is really `\csq@mainlang` that is undefined or something else?

**Comment by moewew** [comment] 2019-11-22 07:41
I'll be away over the weekend, so as far as I'm concerned you can take your time producing that MWE.

If there is no chance of coming up with an MWE with a reasonable amount of work you can send me the full document that produces the error via email (my email address is on the title page of the `biblatex-ext` documentation) it would help if you could include a full `.log` file as well.

**Comment by svenper** [comment] 2019-11-22 18:41
I managed to boil it down to this MWE!

With `\def\csq@mainlang{german}` the two `foreigndisplaycquote` turn English "ibid" into German "ebd".

```tex
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{english}
\setotherlanguage{german}
\usepackage[citetracker=true,style=authoryear-icomp]{biblatex}
\addbibresource{biblatex-examples.bib}
\usepackage[maxlevel=6,strict=true,autostyle=false,autopunct=false,style=german,german=swiss]{csquotes}
\makeatletter
%\def\csq@mainlang{german}
\makeatother

\begin{document}%
this page intentionally left blank%
\newpage
A paraphrasing \parencite[25]{knuth:ct}\par
Another paraphrasing \parencite[50]{knuth:ct}\par
\begin{displaycquote}[75]{knuth:ct}%
A very wise and thoughtful quote%
\end{displaycquote}%
\begin{foreigndisplaycquote}{english}[100]{knuth:ct}%
A very wise and thoughtful quote%
\end{foreigndisplaycquote}%
\newpage
this page intentionally left blank%
\newpage
\printbibliography[heading=none]%
\end{document}%
```

**Comment by moewew** [comment] 2019-11-24 16:35
Thank you very much for the MWE.

I *think* I have tracked down the source of the error and found a fix in https://github.com/josephwright/csquotes/pull/36. It would be great if you could test it (also in your large document; the MWE works fine for me now).

The fact that "ibid." becomes "ebd." in the MWE when we set `\def\csq@mainlang{german}` is not something I'd worry about. Surely, the 'correct' way to fake `\csq@mainlang` here would be `\def\csq@mainlang{english}`. After all, we have `\setmainlanguage{english}` and there are no other language switching commands in the MWE.

```latex
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{english}
\setotherlanguage{german}
\usepackage[citetracker=true,style=authoryear-icomp]{biblatex}
\addbibresource{biblatex-examples.bib}
\usepackage[maxlevel=6,strict=true,autostyle=false,autopunct=false,style=german,german=swiss]{csquotes}
\makeatletter
\def\csq@mainlang{english}
\makeatother

\begin{document}%
this page intentionally left blank%
\newpage
A paraphrasing \parencite[25]{knuth:ct}\par
Another paraphrasing \parencite[50]{knuth:ct}\par
\begin{displaycquote}[75]{knuth:ct}%
A very wise and thoughtful quote%
\end{displaycquote}%
\begin{foreigndisplaycquote}{english}[100]{knuth:ct}%
A very wise and thoughtful quote%
\end{foreigndisplaycquote}%
\newpage
this page intentionally left blank%
\newpage
\printbibliography[heading=none]%
\end{document}%
```

**Comment by svenper** [comment] 2019-11-24 19:41
With #36 applied my large document compiles without error and reads as it should. Thank you!

**Closed as completed** 2019-12-02 18:53 UTC
Labels: bug
